config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'home#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
  get 'contact' => 'home#contact', as: :contact
  post 'contact' => 'home#contact'

  get 'activate/:token' => 'users#activate', as: :activate

  resources :password_resets
  resources :subscriptions, :only => [:index]  
  resources :subjects
  
  resources :instructors do
    resources :comments, :except => [:index], :controller => 'instructors_comments'
    resources :votes, :only => [:up, :down]
    get 'up', :controller => 'instructors_votes', :action => 'up'
    get 'down', :controller => 'instructors_votes', :action => 'down'
  end
  
  resources :courses do
    resources :comments, :except => [:index], :controller => 'courses_comments'
    resources :votes, :only => [:up, :down]
    get 'up', :controller => 'courses_votes', :action => 'up'
    get 'down', :controller => 'courses_votes', :action => 'down'
  end
  
  resources :sections do
    resources :subscriptions, :only => [:create, :destroy]
    get 'subscribe', :controller => 'subscriptions', :action => 'create'
    get 'unsubscribe', :controller => 'subscriptions', :action => 'destroy'
  end

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
	has_and_belongs_to_many :sections
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController 
  before_filter :require_user
  
  def index
    @terms = Term.all
    @term = params.has_key?(:term_id) ? @terms.find { |t| t.id == params[:term_id].to_i } || @terms.first : @terms.first
    @instructors = Instructor.summary({ :page => params[:page], :per_page => 25, :term => @term })
  end
  
  def show
    @terms = Term.all
    @term = params.has_key?(:term_id) ? @terms.find { |t| t.id == params[:term_id].to_i } || @terms.first : @terms.first
    @instructor = Instructor.find(params[:id])
    @subjects = Subject.by_instructor(@instructor)
    @sections = @instructor.sections.find(:all, :include => [:term, { :course => :subject }], :conditions => ['terms.id = ?', @term.id])
    @comments = @instructor.comments.find(:all, :include => [:user])
    @comment = @instructor.comments.build
  end
end

app/views/instructors/index.html.erb
<% title 'instructors' %>

<% content_for :right do %>
  <td id="right">
    <div class="block summary" id="instructors_count_block">
      <h2><%= number_with_delimiter(@instructors.total_entries) %></h2>
      <p>instructors teaching in the</p>
      <p><%= link_to @term.name, instructors_path(:term_id => @term), :title => @term.name, :class => 'tag' %></p>
      <p>term</p>
    </div>

    <div class="block" id="subscriptions_terms_block">
      <h3>Active Terms</h3>
      <% @terms.each do |term| %>
        <%= link_to term.name, instructors_path(:term_id => term), :title => term.name, :class => 'tag' %>
      <% end %>
    </div>
  </td>
<% end %>

<div class="page_title">
  <h2>Instructors</h2>
  <p>The hottest instructors (not visually of course).</p>
</div>

<table class="list instructors">
  <thead>
    <% if @instructors.total_pages > 1 %>
    <tr>
      <td colspan="3"><%= will_paginate @instructors %></td>
    </tr>
    <% end %>
    <tr>
      <th class="vote"></th>
      <th class="instructor_name">Name</th>
      <th class="sections_count">Sections</th>
    </tr>
  </thead>
  <% if @instructors.length > 0 %>

    <% if @instructors.total_pages > 1 %>
    <tfoot>
      <tr>
        <td colspan="3"><%= will_paginate @instructors %></td>
      </tr>
    </tfoot>
    <% end %>

  <tbody>
    <% @instructors.each do |instructor| %>
    <tr>
      <td class="vote">
        <%= link_to 'like', instructor_up_path(instructor, :redirect_to => current_url), :title => 'up vote', :class => current_user.up_voted?(instructor) ? 'liked' : 'like' %>
        <%= link_to 'dislike', instructor_down_path(instructor, :redirect_to => current_url), :title => 'down vote', :class => current_user.down_voted?(instructor) ? 'disliked' : 'dislike' %>
      </td>
      <td class="instructor_name">
        <%= link_to instructor.name, instructor_path(instructor), :title => instructor.name  %>
        <p>
          <span class="points">
            <%= pluralize(instructor.score, 'point', 'points') %>
          </span> |
          <span class="comments">
            <%= link_to pluralize(instructor.comments.size, 'comment', 'comments'),
              instructor_path(instructor, :anchor => 'comments'),
              :title => pluralize(instructor.comments.size, 'comment', 'comments') %>
          </span>
        </p>
      </td>
      <td class="sections_count">
        <%= instructor.sections_count %>
      </td>
    </tr>
    <% end %>
  </tbody>
  <% else %>
  <tbody>
    <tr>
      <td colspan="2"><p>No instructors found.</p></td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/instructors/show.html.erb
<% title @instructor.name %>

<% content_for :right do %>
  <td id="right">
    <div id="instructors_courses_block" class="block summary">
      <h2><%= number_with_delimiter(@sections.size) %></h2>
      <p><%= @instructor.sections.size == 1 ? 'sections' : 'sections' %> taught in the</p>
      <%= link_to @term.name, instructor_path(@instructor, :term_id => @term), :title => @term.name, :class => 'tag' %>
      <p>term</p>
    </div>

    <div class="block" id="instructor_terms_block">
      <h3>Active Terms</h3>
      <% @terms.each do |term| %>
        <%= link_to term.name, instructor_path(@instructor, :term_id => term), :title => term.name, :class => 'tag' %>
      <% end %>
    </div>
    
    <div class="block" id="subjects_block">
      <h3>Subjects</h3>
      <% @subjects.each do |subject| %>
        <%= link_to subject.identifier, subject_path(subject), :title => subject.name, :class => 'tag' %>
      <% end %>
    </div>
  </td>
<% end %>

<div class="page_title">
  <table>
    <tr>
      <td class="vote">
        <%= link_to 'like', instructor_up_path(@instructor), :title => 'up vote', :class => current_user.up_voted?(@instructor) ? 'liked' : 'like' %>
        <%= link_to 'dislike', instructor_down_path(@instructor), :title => 'down vote', :class => current_user.down_voted?(@instructor) ? 'disliked' : 'dislike' %>
      </td>
      <td>
        <h2>
          <%= @instructor.name %>
        </h2>
      </td>
    </tr>
  </table>
  <p>
    <span class="points">
      <%= pluralize(@instructor.score, 'point', 'points') %>
    </span> |
    <span class="comments">
      <%= link_to pluralize(@comments.size, 'comment', 'comments'), url_for(params.merge(:anchor => 'comments')), :title => pluralize(@comments.size, 'comment', 'comments') %>
    </span>
  </p>
</div>

<table class="list">
  <thead>
    <tr>
      <th class="subscribe"></th>
      <th class="course_name">Section Name</th>
      <th class="section_name">Course Name</th>
      <th class="call_number">Call Number</th>
      <th class="subject_name">Subject</th>
      <th class="status">Status</th>
      <th class="open_seats">Open Seats</th>
      <th class="total_seats">Total Seats</th>
    </tr>
  </thead>
  <% if @sections.length > 0 %>
  <tbody>
    <% @sections.each do |section| %>
    <tr id="section_<%= section.id %>">
      <td class="subscribe">
      <% if current_user.subscribed_to?(section) %>
        <%= link_to 'unsubscribe', section_unsubscribe_path(section, :redirect_to => current_url), :class => 'unsubscribe' %>
      <% else %>
        <%= link_to 'subscribe', section_subscribe_path(section, :redirect_to => current_url), :class => 'subscribe' %>
      <% end %>
      </td>
      <td class="section_name">
        <%= section.name %>
      </td>
      <td class="course_name">
        <%= link_to section.course.name, course_path(section.course), :section_id => section.id, :title => section.course.name %>
      </td>      
      <td class="call_number">
        <%= section.call_number %>
      </td>
      <td class="subject_name">
        <%= link_to section.course.subject.identifier, subject_path(section.course.subject), :title => section.course.subject.name %>
      </td>
      <td class="status">
        <%= section.status %>
      </td>
      <td class="open_seats">
        <%= section.open_seats %>
      </td>
      <td class="total_seats">
        <%= section.total_seats %>
      </td>
    </tr>
    <% end %>
  </tbody>
  <% else %>
  <tbody>
    <tr>
    <td colspan="8"><p>Professor is on a sabbatical.</p></td>
    </tr>
  </tbody>
  <% end %>
</table>

<div class="comments">
  <div class="page_info">
    <h3>
      <a name="comments"></a>
      comments (<%= @comments.size %>)
    </h3>
  </div>

  <% form_for :comment, :url => url_for([@instructor, @comment]), :html => { :id => 'comment_form', :class => 'comment_form new' } do |f| %>
    <fieldset>
    <%= f.error_messages %>
    <table class="form">
      <%= render :partial => 'comments/form', :locals => { :f  => f } %>
      <tr>
      <td class="submit">
        <%= f.submit 'add comment', :class => 'button' %>
        <%= link_to 'formatting help', 'http://redcloth.org/hobix.com/textile/quick.html', :popup => true, :title => 'formatting help', :class => 'formatting_help' %>
      </td>
      </tr>
    </table>
    </fieldset>
  <% end %>

  <%= render :partial => 'comments/comments', :locals => { :comments => @comments } %>
</div>