config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'home#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
  get 'contact' => 'home#contact', as: :contact
  post 'contact' => 'home#contact'

  get 'activate/:token' => 'users#activate', as: :activate

  resources :password_resets
  resources :subscriptions, :only => [:index]  
  resources :subjects
  
  resources :instructors do
    resources :comments, :except => [:index], :controller => 'instructors_comments'
    resources :votes, :only => [:up, :down]
    get 'up', :controller => 'instructors_votes', :action => 'up'
    get 'down', :controller => 'instructors_votes', :action => 'down'
  end
  
  resources :courses do
    resources :comments, :except => [:index], :controller => 'courses_comments'
    resources :votes, :only => [:up, :down]
    get 'up', :controller => 'courses_votes', :action => 'up'
    get 'down', :controller => 'courses_votes', :action => 'down'
  end
  
  resources :sections do
    resources :subscriptions, :only => [:create, :destroy]
    get 'subscribe', :controller => 'subscriptions', :action => 'create'
    get 'unsubscribe', :controller => 'subscriptions', :action => 'destroy'
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :courses
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :require_user
  
  def index
    @terms = Term.all
    @term = @terms.first
    if params.has_key?(:term_id)
      term_id = params[:term_id].to_i
      @term = @terms.find { |t| t.id == term_id } || @term
    end
    @subjects = Subject.summary_by_term(@term)
  end
  
  def show
    @subjects = Subject.all
    @subject = @subjects.find { |s| s.id == params[:id].to_i } || @subjects.first
    @terms = Term.all
    @term = @terms.find { |t| t.id == params[:term_id].to_i } || @terms.first
    @courses = Course.summary({ :page => params[:page], :per_page => 50, :subject => @subject, :term => @term })
  end
end

app/views/subjects/index.html.erb
<% title 'subjects' %>

<% content_for :right do %>
  <td id="right">
    <div class="block summary">
      <h2><%= @subjects.size %></h2>
      <p>subjects for the</p>
      <%= link_to @term.name, subjects_path(:term_id => @term), :title => @term.name, :class => 'tag' %>
      <p>term</p>
    </div>

    <% if @terms.size > 1 %>
    <div class="block" id="subjects_block">
      <h3>Active Terms</h3>
      <% @terms.each do |term| %>
        <%= link_to term.name, subjects_path(:term_id => term), :title => term.name, :class => 'tag' %>
      <% end %>
    </div>
    <% end %>
  </td>
<% end %>

<div class="page_title">
  <h2>Subjects</h2>
  <p>All subjects followed by the number of courses.</p>
</div>

<ul class="subjects">
<% @subjects.each do |subject| %>
  <li><%= link_to subject.identifier, subject_path(subject), :title => subject.name %> x <%= subject.courses_count %></li>
<% end %>
</ul>

app/views/subjects/show.html.erb
<% title @subject.name %>

<% content_for :right do %>
  <td id="right">
    <div class="block summary" id="summary_block">
      <h2><%= number_with_delimiter(@courses.total_entries) %></h2>
      <p>courses with subject</p>
      <%= link_to @subject.identifier, subject_path(@subject), :title => @subject.name, :class => 'tag' %>
      <p>for term</p>
      <%= link_to @term.name, subject_path(@subject, :term_id => @term), :title => @term.name, :class => 'tag' %>
    </div>
    
    <% if @terms.size > 1 %>
    <div class="block" id="subjects_block">
      <h3>Active Terms</h3>
      <% @terms.each do |term| %>
        <%= link_to term.name, subject_path(@subject, :term_id => term), :title => term.name, :class => 'tag' %>
      <% end %>
    </div>
    <% end %>
    
    <div class="block" id="subjects_block">
      <h3>Subjects</h3>
      <% @subjects.each do |subject| %>
        <%= link_to subject.identifier, subject_path(subject), :title => subject.name, :class => 'tag' %>
      <% end %>
    </div>
  </td>
<% end %>


<div class="page_title">
  <h2>
    <%= @subject.name %> Courses
  </h2>
  <p>All courses in <%= @subject.name %></p>
</div>

<table class="list">  
  <thead>
    <tr>
      <td colspan="5">
        <%= will_paginate @courses %>
      </td>
    </tr>
    <tr>
      <th class="vote"></th>
      <th class="course_name">Course</th>
      <th class="open_seats">Open Seats</th>
      <th class="total_seats">Total Seats</th>
      <th class="sections_count">Sections</th>
    </tr>
  </thead>
  <% if @courses.size > 0 %>

    <% if @courses.total_pages > 1 %>
    <tfoot>
      <tr>
        <td colspan="5">          
          <%= will_paginate @courses %>          
        </td>
      </tr>
    </tfoot>
    <% end %>

  <tbody>
    <% @courses.each do |course| %>
      <%= render :partial => 'courses/course', :locals => { :course => course } %>
    <% end %>
  </tbody>
  <% else %>
  <tbody>
    <tr>
      <td colspan="5">
      <p>No courses for this subject.</p>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>