config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'home#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
  get 'contact' => 'home#contact', as: :contact
  post 'contact' => 'home#contact'

  get 'activate/:token' => 'users#activate', as: :activate

  resources :password_resets
  resources :subscriptions, :only => [:index]  
  resources :subjects
  
  resources :instructors do
    resources :comments, :except => [:index], :controller => 'instructors_comments'
    resources :votes, :only => [:up, :down]
    get 'up', :controller => 'instructors_votes', :action => 'up'
    get 'down', :controller => 'instructors_votes', :action => 'down'
  end
  
  resources :courses do
    resources :comments, :except => [:index], :controller => 'courses_comments'
    resources :votes, :only => [:up, :down]
    get 'up', :controller => 'courses_votes', :action => 'up'
    get 'down', :controller => 'courses_votes', :action => 'down'
  end
  
  resources :sections do
    resources :subscriptions, :only => [:create, :destroy]
    get 'subscribe', :controller => 'subscriptions', :action => 'create'
    get 'unsubscribe', :controller => 'subscriptions', :action => 'destroy'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Browse Oklahoma State University course catalog.">
    <meta name="author" content="Spike Spiegal">
    <title>
      Cowboy Courses
      <%= yield :title %>
    </title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Cowboy Courses', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <% unless logged_in? %>
            <ul class="nav navbar-nav">
              <li><%= link_to 'Log In', login_path %></li>
              <li><%= link_to 'Sign Up', signup_path %></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav">
              <li><a href="<%= courses_path %>">Courses</a></li>
              <li><a href="<%= subscriptions_path %>">Subscriptions (<%= current_user.subscriptions.count %>)</a></li>

              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Welcome, <%= current_user.name %> <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Foo</a></li>
                    <li><a href="#">Bar</a></li>
                    <li class="divider"></li>
                    <li><%= link_to 'Log Out', logout_path %></li>
                  </ul>
                </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <% unless flash.empty? %>
        <% flash.each do |k, v| %>
          <div class="alert alert-<%= k %>" role="alert">
            <%= v %>
          </div>
        <% end %>
      <% end %>

      <%= yield %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>